### ISSUE TITLE
Service Desk

### ISSUE THREAD

**Issue by dados77** [everit-org/jira-timetracker-plugin#252]
It is possible to use TimeTracker for Service Desk project?

**Comment by bordatesz** [comment]
Hi there!

Can you give me some further technical information as:
- Which Timetracker, JIRA and Service Desk version do you use?

I tested Timertracker 3.x with our JIRA 7 and with JIRA Service Desk 3 and it's worked. Each service desk you create with JIRA Service Desk is based on a JIRA project. Service Desk provide additional components, workflows, etc., but this does not affect the work logging functionality of JIRA. If the user has the requied permissions for the SD project (browse project, work on issues, etc.), he/she can use all the features of the Timetracker without any problems.

**Comment by dados77** [comment]
Hi.

Thanks for reply. We use same configuration that you Jira 7.1.0 build 71003 and Service Desk 3.1.7
we have a lot of project and costumized user Group. For istance user Group that have access to service desk is not reported in user Group that Timetracker offers

**Comment by bordatesz** [comment]
If I understand correctly, you have a JIRA group with some Service Desk role, eg. 'Service Desk Team'. 
Could you tell me where is the problem exactly occours in the Timetracker? Eg.: 
- You can't choose this group in the Reporting's group picker? 
- You can't choose this group on the Timetracker admin site? 
- Maybe the members of this group can't see add/see worklog on Timetracker page?

**Comment by dados77** [comment]
Yes, it is correct we have a Group name service-desk-agent
- When I open reporting's Group I cannot see that Group name. 
- Yes I can to decide to assign use of Timetracker only to this grupo, so on global configuration I see this user Group
- User of this Group when use timetracker cannot see anything associated by them name

**Comment by dados77** [comment]
Sorry, I understand the misconfiguration.

I new on Jira software and I see that this plugin work on worklog. On project that don't display anything there are nor worklog registered data so there are anythings to display.

I search for a plugin that don't use a worklog but calcuate how many time has been assigned to a specify user or how many time stay on particular state

**Comment by bordatesz** [comment]
Yes, the Timetracker plugin designed and developed for work log management in JIRA. So your Service Desk Agents can log easily the time that they worked on a customer request, and you can make reports about these time efforts. But the plugin does not calculate issue assign number or in state time. For this functionality I can advise you this article: [Link](https://confluence.atlassian.com/jira062/tracking-the-time-taken-for-each-workflow-transition-588581465.html). 

It seem this problem not affect our Timetracker, so if you agree, I'm close this isse.
By the way, is it possible that you have sent a feedback with the same question to us yesterday? (before creating this issue here)
