### ISSUE TITLE
Fix minutes representation as minutes and not decimal fraction of hour

### ISSUE THREAD

**Issue by a-aristar** [everit-org/jira-timetracker-plugin#425]
Hi!

In some cases Timetracker window displays minutes as minutes and sometimes as decimal fraction of hour. For instance, 30 minutes are always displayed as 0.5h
Is it possible to fix minutes representation in minutes format. Various representation is quite inconvenient.

**Comment by bordatesz** [comment]
Hi there,
In the latest version, Timetracker adapts the JIRA time format. Time spent, Duration and Remaining will be displayed in hours if it has been set in the [Time Tracking settings](https://confluence.atlassian.com/adminjiraserver071/configuring-time-tracking-802593086.html).
- In case of hours time format, JIRA uses hour format and fractions only in quarters, eg. 03:30 will be 3.5h, but 03:42 will be 3h 42m. 
- In case of pretty format, Timetracker shortens the times, so instead of "20 minutes" you will see "20m" always, so I suggest you set the pretty format in your JIRA Time Tracking configuration.

![image](https://cloud.githubusercontent.com/assets/5459077/20344243/3e3bd4bc-abf2-11e6-85c9-e2bf868a774c.png)

**Comment by bordatesz** [comment]
Hi @a-aristar 
Was my previous comment helpful?

**Comment by a-aristar** [comment]
@bordatesz thanks a lot. This is exactly what I asked for.

**Comment by bordatesz** [comment]
Hi @a-aristar ,
Glad I could help!
If you are satisfied with our Timetracker, please write a review on the [Marketplace](https://marketplace.atlassian.com/plugins/org.everit.jira.timetracker.plugin/server/overview). We really appreciate it!

Regards,
Attila
