### ISSUE TITLE
Start time should jump back to beginning of day if we switch day without editing

### ISSUE THREAD

**Issue by balazs-zsoldos** [everit-org/jira-timetracker-plugin#460]
If we switch a day

- and we are currently editing an item, the start, end and duration fields should stay as they are
- and we are not editing an item currently, the start-time should be the end of the last record on the day or the beginning of the day if there is no record

If we switch the date and we are not editing currently, the duration (or end of time) should be set to a full working day by default.

If we switch the date and the duration field was active previously (not the end-time), the duration field should stay active (the same if we save an entry).

**Comment by bordatesz** [comment]
"If we switch a day and we are currently editing an item, the start, end and duration fields should stay as they are / and we are not editing an item currently, the start-time should be the end of the last record on the day or the beginning of the day if there is no record" - Fixed in the latest version.

"If we switch the date and the duration field was active previously (not the end-time), the duration field should stay active (the same if we save an entry)." - Fixed in the latest verions.

"If we switch the date and we are not editing currently, the duration (or end of time) should be set to a full working day by default." - We dropped this proposal.
