### ISSUE TITLE
Wrong remaining time when logging in sub-tasks

### ISSUE THREAD

**Issue by bcersows** [everit-org/jira-timetracker-plugin#507]
Hey guys.

There's a little -- but really annoying -- bug when using sub tasks and logging in them.
On the main issue, the remaining time label is not getting updated (the progress bar is, though).

See the following screenshots:
![image](https://user-images.githubusercontent.com/1199637/29875680-048b53ec-8d9b-11e7-9592-ce1e1c5def37.png)

![image](https://user-images.githubusercontent.com/1199637/29875732-267d78c2-8d9b-11e7-94da-2a2e0316f89c.png)

The label still states `1w 1d 5h`, instead of the correct `1w 1d 2h`.

Thanks for the plugin!
Cheers, @bcersows

**Comment by bordatesz** [comment]
Hello @bcersows ,
Does the sub-task Issue have an estimated time? 

Note, that in JIRA the parent time remaining time will decrease if:
1. The parent had time logged against it, or 
2. The parents remaining time can only be burnt down by the amount it inherited from the subtask's time remaining.

**Comment by bcersows** [comment]
Hey @bordatesz,

yes, the subtask has 3 hours logged against it (which are correctly gathered for the `logged` bar).
It did not have an estimate set. But I even after editing to add one, the remaining time does not calculate directly. The added estimate of the subtask is added to the main issue's estimate, though.

Cheers

**Comment by bordatesz** [comment]
Unfortunately, by Atlassian's design, this is the expected behaviour in this case.
Simply put, you need to estimate (Original Estimate) the parent and the sub-task issue before you start to work on them to behave as you expected here. (So this is not related to our Timetracker, this is the default.) 
For more information,  see the following links:

- https://jira.atlassian.com/browse/JRA-31017
- https://jira.atlassian.com/browse/JRA-40871
- https://jira.atlassian.com/browse/JRA-25057
- https://community.atlassian.com/t5/JIRA-Software-questions/Rapid-Board-time-estimates-with-sub-tasks/qaq-p/278262

**Comment by bcersows** [comment]
Thanks a lot for your explanations. :)
